include colors.conf
# =========================
# Fonts
# =========================
font_family        Iosevka Term
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size          10


# =========================
# Cursor
# =========================
cursor_shape            block
cursor_shape_unfocused  underline
cursor_trail            1


# =========================
# Behavior
# =========================
scrollback_lines        5000
scrollbar               never
enable_audio_bell       no
allow_remote_control    yes


# =========================
# Background
# =========================
# background               #2a2a2a
# background_opacity 0.8
# bacgroynd_blur 32
# background_image         /home/cypher/Pictures/Wallpapers/streetlight.jpg
# background_image_layout  scaled 
# tiled/scaled/clamped/centered
# background_image_opacity 0.80


# =========================
# Tabs
# =========================
tab_bar_edge             bottom
tab_bar_style            powerline
tab_powerline_style      slanted
tab_bar_align            left


# BEGIN_KITTY_THEME
# Farin
include current-theme.conf
# END_KITTY_THEME